[shortcuts]
"Left" = "GoToPrevCharacter"
"Shift+Left" = "GoToPrevCharacterSelect"
"Right" = "GoToNextCharacter"
"Shift+Right" = "GoToNextCharacterSelect"
"Up" = "GoToPrevLine"
"Shift+Up" = "GoToPrevLineSelect"
"Down" = "GoToNextLine"
"Shift+Down" = "GoToNextLineSelect"
"Enter" = "Enter"
"Backspace" = "Backspace"
"Delete" = "Delete"
"Home" = "GoToLineStart"
"End" = "GoToLineEnd"
"Ctrl+Shift+F7" = "InsertHighlight"
"Cmd+Shift+F7" = "InsertHighlight"
"Ctrl+S" = "Save"
"Cmd+S" = "Save"
"Ctrl+Z" = "Undo"
"Cmd+Z" = "Undo"
"Ctrl+Shift+Z" = "Redo"
"Cmd+Shift+Z" = "Redo"
"Ctrl+Home" = "GoToBufferStart"
"Cmd+Home" = "GoToBufferStart"
"Ctrl+End" = "GoToBufferEnd"
"Cmd+End" = "GoToBufferEnd"
"Ctrl+F" = "Search"
"Cmd+F" = "Search"
"Ctrl+R" = "Replace"
"Cmd+R" = "Replace"
