pub(crate) mod frame_history;
pub(crate) mod helppanel;
pub(crate) mod search_result_panel;
pub(crate) mod options_dialog;
pub(crate) mod search_toolbar;
pub(crate) mod textpane;
pub(crate) mod theme;
pub(crate) mod tools;
pub(crate) mod action;
